=== alanicolas90/Programacion/MARKUP/ProyectML Alan Mikolajczyk/PROYECTO TOCHO/public_html/schema/schema1.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema    version="1.0"
              xmlns:xs="http://www.w3.org/2001/XMLSchema"
              elementFormDefault="qualified">

    <xs:element name="fruitStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="executives">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="worker" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" minOccurs="1"/>
                                        <xs:element name="surname" minOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="id_numer">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:pattern value="[0-9][0-9][0-9][0-9]"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="charge">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="CEO"/>
                                                <xs:enumeration value="RRHH"/>
                                                <xs:enumeration value="President"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="shops">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="shop" minOccurs="1" maxOccurs="unbounded"> 
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="workers" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="worker" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="name" minOccurs="1"/>
                                                                <xs:element name="surname" minOccurs="1"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="id_numer" type="xs:int"/>
                                                            <xs:attribute name="charge" type="xs:string"/>
                                                            <xs:attribute name="nationality" type="xs:string"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nr" type="xs:int"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alanicolas90/Programacion/MARKUP/finalassignement2term/public_html/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->


<fruitStore name="Defecto Fruta"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="schema1.xsd">
    <executives>
        <worker id_numer="0001" charge="CEO">
            <name>Alan</name>
            <surname>Mikolajczyk</surname>
        </worker>
        <worker id_numer="1001" charge="RRHH">
            <name>Juan</name>
            <surname>Manute</surname>
        </worker>
    </executives>
    <shops>
        <shop nr="1">
            <workers>
                <worker id_numer="1002" charge="cashier" nationality="ES">
                    <name>Jose</name>
                    <surname>Manuel</surname>
                </worker>
                <worker id_numer="1003" charge="dependant" nationality="GB">
                    <name>Pepe</name>
                    <surname>Murray</surname>
                </worker>
            </workers>
        </shop>
        <shop nr="2">
            <workers>
                <worker id_numer="2001" charge="cashier"  nationality="ES">
                    <name>Sara</name>
                    <surname>Socas</surname>
                </worker>
                <worker id_numer="2001" charge="cashier" nationality="ES">
                    <name>Julia</name>
                    <surname>Bastinazo</surname>
                </worker>
                <worker id_numer="2001" charge="dependant" nationality="PL">
                    <name>Sarah</name>
                    <surname>Moew</surname>
                </worker>
            </workers>
        </shop>
        <shop nr="3">
            <workers>
                <worker id_numer="3001" charge="dependant" nationality="ES">
                    <name>Almudena</name>
                    <surname>Tirain</surname>
                </worker>
                <worker id_numer="3001" charge="cashier" nationality="EN">
                    <name>George</name>
                    <surname>Jungle</surname>
                </worker>
            </workers>
        </shop>     
    </shops>
</fruitStore>
