=== alanicolas90/Programacion/MARKUP/finalassignement2term/public_html/XSD/schema2.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="FruitStore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Products">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="Product">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="color" type="xs:string" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="icon" type="xs:string" />
                                        <xs:element name="properties">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="vitamin" use="required">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="[A-Z]"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="prices">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="unbounded" name="price" type="xs:decimal" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="origin">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="country" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="continent" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="LATAM"/>
                                                            <xs:enumeration value="Asia"/>
                                                            <xs:enumeration value="Europe"/>
                                                            <xs:enumeration value="North America"/>
                                                            <xs:enumeration value="Oceania"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="category" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="fruit"/>
                                                <xs:enumeration value="vegetable"/>
                                                <xs:enumeration value="prepared"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="season" use="required" >
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="summer"/>
                                                <xs:enumeration value="autumn"/>
                                                <xs:enumeration value="winter"/>
                                                <xs:enumeration value="spring"/>
                                                <xs:enumeration value="all"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alanicolas90/Programacion/MARKUP/finalassignement2term/public_html/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->



<FruitStore
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema2.xsd">
    <Products>
        <Product category="fruit" season="summer">
            <name color="green">grapes</name>
            <icon>üçá</icon>
            <properties vitamin="K">high antioxidant</properties>
            <prices>
                <price>2.34</price>
            </prices>
            <origin continent="LATAM">
                <country>Chile</country>
            </origin>
        </Product>
        
        
        <Product category="fruit" season="all">
            <name>melon</name>
            <icon>üçà</icon>
            <properties vitamin="A">beta carotene</properties>
            <prices>
                <price>0.84</price>
            </prices>
            <origin continent="LATAM">
                <country>Brazil</country>
            </origin>
        </Product>
        
        
        <Product category="fruit" season="summer">
            <name>Watermelon</name>
            <icon>üçâ</icon>
            <properties vitamin="A">Lycopene</properties>
            <prices>
                <price>0.84</price>
            </prices>
            <origin continent="Asia">
                <country>India</country>
            </origin>
        </Product>
        
        
        <Product category="fruit" season="autumn">
            <name>lemon</name>
            <icon>üçã</icon>
            <properties vitamin="C"></properties>
            <prices>
                <price>0.84</price>
            </prices>
            <origin continent="Asia">
                <country>India</country>
            </origin>
        </Product>
        
        <Product category="fruit" season="winter">
            <name>apple</name>
            <icon color="red">üçé</icon>
            <properties vitamin="K">antioxidants</properties>
            <prices>
                <price>0.84</price>
                <price>1.34</price>
            </prices>
            <origin continent="North America">
                <country>Canada</country>
            </origin>
        </Product>
        
        
        <Product category="vegetable" season="all">
            <name>carrot</name>
            <icon>ü•ï</icon>
            <properties vitamin="K">carotene</properties>
            <prices>
                <price>0.65</price>
            </prices>
            <origin continent="Asia">
                <country>Afghanistan</country>
            </origin>
        </Product>
        
        <Product category="vegetable" season="autumn">
            <name>cucumber</name>
            <icon>ü•í</icon>
            <properties vitamin="K">manganese</properties>
            <prices>
                <price>0.80</price>
            </prices>
            <origin continent="Asia">
                <country>India</country>
            </origin>
        </Product>
        
        <Product category="vegetable" season="autumn">
            <name>brocoli</name>
            <icon>ü•¶</icon>
            <properties vitamin="K">potassium</properties>
            <prices>
                <price>2.30</price>
            </prices>
            <origin continent="Europe">
                <country>England</country>
            </origin>
        </Product>
        
        <Product category="prepared" season="all">
            <name>eggs</name>
            <icon>ü•ö</icon>
            <properties vitamin="D">selenium</properties>
            <prices>
                <price>2.76</price>
            </prices>
            <origin continent="Europe">
                <country>Spain</country>
            </origin>
        </Product>
        
        <Product category="prepared" season="all">
            <name>rice</name>
            <icon>üçö</icon>
            <properties vitamin="B">carbohydrates</properties>
            <prices>
                <price>2.76</price>
            </prices>
            <origin continent="Asia">
                <country>China</country>
            </origin>
        </Product>
        
        <Product category="prepared" season="all">
            <name>salt</name>
            <icon>üßÇ</icon>
            <properties vitamin="F">sick pump</properties>
            <prices>
                <price>1.34</price>
            </prices>
            <origin continent="Asia">
                <country>China</country>
            </origin>
        </Product>
        
        <Product category="prepared" season="all">
            <name>honey</name>
            <icon>üçØ</icon>
            <properties vitamin="E">niacin</properties>
            <prices>
                <price>8.65</price>
            </prices>
            <origin continent="Europe">
                <country>Spain</country>
            </origin>
        </Product>
        
    </Products>
</FruitStore>
